# assisgnment 2

# 1.

In [2]:
import numpy as np
import pandas as pd
from random import randint

In [3]:
a=np.zeros(10)
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

# 2.

In [4]:
a=np.zeros(10)
a[4]=1
a

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

# 3.

In [5]:
a=np.arange(0,9).reshape(3,3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

# 4.

In [6]:
a=np.random.random((3,3,3))
a

array([[[0.63908698, 0.28124649, 0.10981447],
        [0.72436361, 0.30294672, 0.4315311 ],
        [0.51862404, 0.03478347, 0.25815565]],

       [[0.61435871, 0.73432988, 0.55105129],
        [0.73976925, 0.08190937, 0.08462448],
        [0.26081519, 0.87760698, 0.15544351]],

       [[0.79973987, 0.73687652, 0.19908908],
        [0.1144398 , 0.30944879, 0.17426791],
        [0.0525113 , 0.15481653, 0.09599723]]])

# 5.

In [7]:
a=np.random.random((5,3))
print(a)
b=np.random.random((3,2))
print(b)
c=np.dot(a,b)
c

[[0.91493526 0.30252016 0.75745635]
 [0.08542514 0.59698236 0.98011098]
 [0.83148076 0.76166084 0.09045511]
 [0.07581224 0.98214858 0.90501206]
 [0.51305502 0.36266271 0.06077878]]
[[0.42697978 0.82463103]
 [0.00768472 0.74084661]
 [0.78619536 0.36828084]]


array([[0.98849231, 1.25756171],
       [0.81162115, 0.87367267],
       [0.43199401, 1.28325157],
       [0.75143411, 1.12343718],
       [0.26963508, 0.71414219]])

In [8]:
a=np.zeros((5,5))
a+=np.arange(0,5)
a

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

In [9]:
a=np.random.random(10)
print(a)
a.sort()
print(a)

[0.32977919 0.39831619 0.98483206 0.24614572 0.78517939 0.7551715
 0.63941848 0.2651051  0.44481476 0.96763519]
[0.24614572 0.2651051  0.32977919 0.39831619 0.44481476 0.63941848
 0.7551715  0.78517939 0.96763519 0.98483206]


In [15]:
x=np.array([[10,20,30],[30,40,50]])
print(x)

y=x.mean(axis=0)
print(y)

z=y-x
print(z)

[[10 20 30]
 [30 40 50]]
[20. 30. 40.]
[[ 10.  10.  10.]
 [-10. -10. -10.]]


In [18]:
x=np.array([[1,2,3],[5,6,7],[7,5,8,]])
y=np.array([[3,4,4],[6,7,8],[2,4,5]])
print(x)
print(y)
z=x.dot(y)
print(z)
np.diagonal(z)

[[1 2 3]
 [5 6 7]
 [7 5 8]]
[[3 4 4]
 [6 7 8]
 [2 4 5]]
[[ 21  30  35]
 [ 65  90 103]
 [ 67  95 108]]


array([ 21,  90, 108])

In [27]:
x=np.random.random(10)
print(x)
x.sort()
print(x)

[0.09745176 0.75750823 0.41070684 0.02304135 0.84280446 0.2459432
 0.70842512 0.29800218 0.89416707 0.67005905]
[0.02304135 0.09745176 0.2459432  0.29800218 0.41070684 0.67005905
 0.70842512 0.75750823 0.84280446 0.89416707]
