# numpy

In [2]:
import numpy as np
a = np.array([1,2,3])
a

array([1, 2, 3])

In [6]:
print(a.data)
print(a.dtype)
print(a.shape)
print(type(a))

int32
(3,)
<class 'numpy.ndarray'>


In [8]:
b=np.array([(1,2,3),(4,5,6)])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
print(b)
print(b.data)
print(b.dtype)
print(type(a))

[[1 2 3]
 [4 5 6]]
int32
<class 'numpy.ndarray'>


In [16]:
c=np.array(([(1,2,3),(4,5,6),(7,8,9)],[(1,2,3),(4,5,6),(7,8,9)]))
c

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [18]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [19]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [21]:
np.random.random((2,2))

array([[0.82587351, 0.39274927],
       [0.77988373, 0.08530059]])

In [22]:
np.empty((3,3))

array([[0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 7.01573217e-321],
       [8.70018274e-313, 0.00000000e+000, 7.05138130e-315]])

In [23]:
np.empty((3,3))

array([[0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 7.01573217e-321],
       [8.70018274e-313, 0.00000000e+000, 7.05138130e-315]])

In [24]:
np.full((2,2),9)

array([[9, 9],
       [9, 9]])

In [29]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [33]:
x=np.arange(1,11)
print(x)
x=x.astype(float)
print(x)
print(x.dtype)

[ 1  2  3  4  5  6  7  8  9 10]
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
float64


In [37]:
x=np.ones((3,4))
print(x)
y=np.random.random((3,4))
print(y)
z=x+y
print(z)
print(z.shape)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[0.61755026 0.90388403 0.37887159 0.33025383]
 [0.38694188 0.44494182 0.35653018 0.84685276]
 [0.33404338 0.17877607 0.35325015 0.827262  ]]
[[1.61755026 1.90388403 1.37887159 1.33025383]
 [1.38694188 1.44494182 1.35653018 1.84685276]
 [1.33404338 1.17877607 1.35325015 1.827262  ]]
(3, 4)


In [46]:
x=np.ones((3,4))
print(x)
x.T
print(x.shape)
y=np.ones(3)
print(y)



[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
(3, 4)
[1. 1. 1.]


In [55]:
x=np.random.random((3,4))
print(x)
y=np.random.random((3,4))*3
print(y)
z=x*y
print(z)


[[0.86242891 0.13744716 0.61808614 0.93064265]
 [0.33696473 0.06556505 0.00475754 0.730141  ]
 [0.15038508 0.38842067 0.38924435 0.59446491]]
[[2.49070704 2.36261038 2.28212366 1.75971277]
 [0.55885632 2.48492992 2.19930294 1.62830175]
 [1.11744089 2.10786559 1.26601923 0.06029766]]
[[2.14805776 0.32473408 1.410549   1.63766376]
 [0.18831487 0.16292455 0.01046328 1.18888986]
 [0.16804644 0.81873857 0.49279083 0.03584484]]


In [73]:
x=np.array([(1,2,3),(4,5,6)])
y=np.array([(2,4,6),(1,3,5)])
z=np.dot(x,y)


ValueError: shapes (2,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

[[2 4 6]
 [1 3 5]]


In [66]:
)
z

ValueError: shapes (2,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)